In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [7]:
data = np.random.randint(1,20,2)
data


array([12,  1])

In [8]:
data = np.zeros([2,2])
data

array([[0., 0.],
       [0., 0.]])

In [13]:
data = np.array([[1,2,3],[4,5,6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
data = np.array([[1,2,3],[2,3,4]])
data

array([[1, 2, 3],
       [2, 3, 4]])

In [15]:
data[1][1]

3

In [11]:
import numpy as np
import pandas as pd

In [12]:
df = pd.read_excel("./data/bangalore_cp.xlsx")
df.head()

Name                       Display Name  \
0    2S PRECISION TOOLS & COMPONENTS    2S PRECISION TOOLS & COMPONENTS   
1         3M INDIA LIMITED - GUJARAT         3M INDIA LIMITED - GUJARAT   
2              3M INDIA LIMITED - KA              3M INDIA LIMITED - KA   
3  ABHINANDAN PLASTICS INDIA PVT LTD  ABHINANDAN PLASTICS INDIA PVT LTD   
4        ABINANDAN PETROPACK PVT LTD        ABINANDAN PETROPACK PVT LTD   

                               Tags                          Email  \
0  Bangalore Trade Receivables - CP             2sptools@gmail.com   
1  Bangalore Trade Receivables - CP           btammangowda@mmm.com   
2  Bangalore Trade Receivables - CP           btammangowda@mmm.com   
3  Bangalore Trade Receivables - CP  abhinandan.plastics@gmail.com   
4  Bangalore Trade Receivables - CP      abhinandan.mrpl@gmail.com   

       PAN No  Remarks  
0  AAAFZ4003E      NaN  
1  AAACB5724H      NaN  
2  AAACB5724H      NaN  
3  AABCA7082Q  Updated  
4  AABCA7911Q  Updated

In [13]:
df.isnull().sum()

Name              0
Display Name      0
Tags              0
Email            25
PAN No            3
Remarks         276
dtype: int64

In [11]:
df.drop(["Display Name","Remarks"],axis=1)

Name                              Tags  \
0      2S PRECISION TOOLS & COMPONENTS  Bangalore Trade Receivables - CP   
1           3M INDIA LIMITED - GUJARAT  Bangalore Trade Receivables - CP   
2                3M INDIA LIMITED - KA  Bangalore Trade Receivables - CP   
3    ABHINANDAN PLASTICS INDIA PVT LTD  Bangalore Trade Receivables - CP   
4          ABINANDAN PETROPACK PVT LTD  Bangalore Trade Receivables - CP   
..                                 ...                               ...   
286                      VSP PACKAGING  Bangalore Trade Receivables - CP   
287             Venkateshwara Polymers  Bangalore Trade Receivables - CP   
288                       WIN POLYMERS  Bangalore Trade Receivables - CP   
289                WINPLAST INDUSTRIES  Bangalore Trade Receivables - CP   
290               YEKADANTHA PACKAGING  Bangalore Trade Receivables - CP   

                             Email      PAN No  
0               2sptools@gmail.com  AAAFZ4003E  
1             btammangowda@mmm.com  AAACB5724H  
2             btammangowda@mmm.com  AAACB5724H  
3    abhinandan.plastics@gmail.com  AABCA7082Q  
4        abhinandan.mrpl@gmail.com  AABCA7911Q  
..                             ...         ...  
286              vsppack@gmail.com  AFSPS7799K  
287       cmvishwanath74@gmail.com  AHMPV9702D  
288      vanaja@saraswathiplast.in  AFIPC5531K  
289      vanaja@saraswathiplast.in  AABFW5767H  
290  yekadanthapackaging@gmail.com  AACFY1258Q  

[291 rows x 4 columns]

In [12]:
df.describe()

Name        Display Name  \
count                  291                 291   
unique                 289                 289   
top     KRISHNA INDUSTRIES  KRISHNA INDUSTRIES   
freq                     2                   2   

                                    Tags                 Email      PAN No  \
count                                291                   266         288   
unique                                 1                   238         278   
top     Bangalore Trade Receivables - CP  seshadrikn@gmail.com  AAACG7300C   
freq                                 291                     4           2   

        Remarks  
count        15  
unique        1  
top     Updated  
freq         15

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 291 entries, 0 to 290
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Name          291 non-null    object
 1   Display Name  291 non-null    object
 2   Tags          291 non-null    object
 3   Email         266 non-null    object
 4   PAN No        288 non-null    object
 5   Remarks       15 non-null     object
dtypes: object(6)
memory usage: 13.8+ KB


In [16]:
df.max([""])

TypeError: unhashable type: 'list'

In [20]:
df.corr()

Empty DataFrame
Columns: []
Index: []

In [21]:
df.skew()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_15136\1665899112.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.skew()


Series([], dtype: float64)

In [19]:
df.summary()

AttributeError: 'DataFrame' object has no attribute 'summary'

In [22]:
df.columns

Index(['Name', 'Display Name', 'Tags', 'Email', 'PAN No', 'Remarks'], dtype='object')

In [23]:
df.groupby(["Name","Remarks"])